### GET FRIENDs
GET http://localhost:8383/friends

### GET FRIEND
GET http://localhost:8383/friends/fish


### ADD A FRIEND
POST http://localhost:8383/add-friend
Content-Type: application/json

{
    "name": "id",
    "status": "enemy"
}

### UPDATE STATUS OF A FRIEND
PATCH http://localhost:8383/change-status
Content-Type: application/json

{
    "name": "car",
    "newStatus": "friend"
}


###DELETE A FRIEND
DELETE http://localhost:8383/friends
Content-Type: application/json

{
    "name": "id"
}


